blank_issues_enabled: false
contact_links:
  - name: Questions and chat
    url: https://github.com/Neil2222/rebirth/discussions
    about: Ask a question or talk an idea through before making it an issue.
